#ifndef BATCH_TYPES_H
#define BATCH_TYPES_H

#include <stdint.h>

#define BATCH_NO_PARAM -1
#define MAX_EXTRA_PARAMS 4
#ifndef MAX_BATCH_SIZE
#define MAX_BATCH_SIZE 2000
#endif

#ifndef WAKSMAN_THRESHOLD
#define WAKSMAN_THRESHOLD MAX_BATCH_SIZE
#endif


typedef struct {
    int32_t idx1;                           // First entry index
    int32_t idx2;                           // Second entry index (or BATCH_NO_PARAM)
    int32_t extra_params[MAX_EXTRA_PARAMS]; // Additional parameters
} BatchOperation;

typedef enum {
    // Comparator operations
    OP_ECALL_COMPARATOR_JOIN_ATTR,
    OP_ECALL_COMPARATOR_PAIRWISE,
    OP_ECALL_COMPARATOR_END_FIRST,
    OP_ECALL_COMPARATOR_JOIN_THEN_OTHER,
    OP_ECALL_COMPARATOR_ORIGINAL_INDEX,
    OP_ECALL_COMPARATOR_ALIGNMENT_KEY,
    OP_ECALL_COMPARATOR_PADDING_LAST,
    OP_ECALL_COMPARATOR_DISTRIBUTE,
    
    // Transform operations
    OP_ECALL_TRANSFORM_SET_LOCAL_MULT_ONE,
    OP_ECALL_TRANSFORM_ADD_METADATA,
    OP_ECALL_TRANSFORM_SET_INDEX,
    OP_ECALL_TRANSFORM_INIT_LOCAL_TEMPS,
    OP_ECALL_TRANSFORM_INIT_FINAL_MULT,
    OP_ECALL_TRANSFORM_INIT_FOREIGN_TEMPS,
    OP_ECALL_TRANSFORM_TO_SOURCE,
    OP_ECALL_TRANSFORM_TO_START,
    OP_ECALL_TRANSFORM_TO_END,
    OP_ECALL_TRANSFORM_SET_SORT_PADDING,
    OP_ECALL_TRANSFORM_SET_JOIN_ATTR,
    OP_ECALL_TRANSFORM_INIT_DST_IDX,
    OP_ECALL_TRANSFORM_INIT_INDEX,
    OP_ECALL_TRANSFORM_MARK_ZERO_MULT_PADDING,
    OP_ECALL_TRANSFORM_CREATE_DIST_PADDING,
    OP_ECALL_TRANSFORM_INIT_COPY_INDEX,
    OP_ECALL_TRANSFORM_COMPUTE_ALIGNMENT_KEY,
    OP_ECALL_INIT_METADATA_NULL,
    
    // Window operations
    OP_ECALL_WINDOW_SET_ORIGINAL_INDEX,
    OP_ECALL_WINDOW_COMPUTE_LOCAL_SUM,
    OP_ECALL_WINDOW_COMPUTE_LOCAL_INTERVAL,
    OP_ECALL_WINDOW_COMPUTE_FOREIGN_SUM,
    OP_ECALL_WINDOW_COMPUTE_FOREIGN_INTERVAL,
    OP_ECALL_WINDOW_PROPAGATE_FOREIGN_INTERVAL,
    OP_ECALL_WINDOW_COMPUTE_DST_IDX,
    OP_ECALL_WINDOW_INCREMENT_INDEX,
    OP_ECALL_WINDOW_EXPAND_COPY,
    OP_ECALL_WINDOW_UPDATE_COPY_INDEX,
    
    // Update operations
    OP_ECALL_UPDATE_TARGET_MULTIPLICITY,
    OP_ECALL_UPDATE_TARGET_FINAL_MULTIPLICITY,
    
    // Concat operations
    OP_ECALL_CONCAT_ATTRIBUTES
} OpEcall;

#endif // BATCH_TYPES_H