SELECT *
FROM users1, users2, users3, users4
WHERE users2.U2_REGTIME > users1.U1_REGTIME - 4
AND users2.U2_REGTIME < users1.U1_REGTIME
AND users3.U3_REGTIME > users1.U1_REGTIME - 4
AND users3.U3_REGTIME < users1.U1_REGTIME
AND users4.U4_REGTIME > users2.U2_REGTIME - 4
AND users4.U4_REGTIME < users2.U2_REGTIME;
