#!/usr/bin/env python3
"""
Export a query-listings appendix from the committed SQL files.

Reads input/queries/higgs_*.sql directly, so the listing cannot drift from what
the engine and the SQLite reference actually run.  Structure (arity, band vs
equality predicates, topology) is derived from the SQL, not hand-written.

Usage:  python3 scripts/export_queries.py [output.md]
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
QDIR = ROOT / 'input' / 'queries'
DEFAULT_OUT = ROOT / 'benchmarks' / 'higgs_queries.md'

# Paper name -> query file stem, in presentation order.
GROUPS = [
    ('Application multi-way band joins',
     'Follower graph (equality) combined with the activity-time band. These are '
     'the queries the paper reports as HQ3/HQ4/HQ5.',
     [('HQ3', 'higgs_tw3_w4'), ('HQ4', 'higgs_tw4_w4'), ('HQ5', 'higgs_tw5_w4')]),
    ('Scalability microbenchmark — hop chain',
     'A chain of `e` band edges over `e+1` self-joined `users` copies. Under a '
     'fixed window the chain *shrinks* with depth: an 8-link chain within 4 s is '
     'restrictive, so output decays as `e` grows.',
     [(f'chain e={e}', f'higgs_hop{e}_w4') for e in range(1, 9)]),
    ('Scalability microbenchmark — balanced binary tree',
     'A balanced binary tree of `e` band edges over `e+1` self-joined `users` '
     'copies. Output *grows* with depth (shallow paths compose), so this family '
     'is the stress case.',
     [(f'tree e={e}', f'higgs_btree{e}_w4') for e in range(1, 9)]),
]

FROM_RE = re.compile(r'FROM\s+(.*?)\s+WHERE', re.IGNORECASE | re.DOTALL)
EQ_RE = re.compile(r'(\w+)\.(\w+)\s*=\s*(\w+)\.(\w+)')
BAND_RE = re.compile(r'(\w+)\.(\w+)\s*([<>])\s*(\w+)\.(\w+)\s*(?:([-+])\s*(\d+))?')


def analyse(sql):
    """Derive (tables, equality-predicate count, band-predicate count)."""
    m = FROM_RE.search(sql)
    tables = [t.strip() for t in m.group(1).split(',')] if m else []

    conds = [c.strip() for c in re.split(r'\bAND\b', sql.split('WHERE', 1)[1],
                                         flags=re.IGNORECASE)] if 'WHERE' in sql else []
    eq = sum(1 for c in conds if EQ_RE.search(c))
    ineq = sum(1 for c in conds if not EQ_RE.search(c) and BAND_RE.search(c))
    # A band edge is a matched pair of inequalities on the same column pair.
    return tables, eq, ineq // 2


def describe(tables, eq, band):
    parts = [f'k={len(tables)}']
    if band:
        parts.append(f'{band} band edge' + ('s' if band != 1 else ''))
    if eq:
        parts.append(f'{eq} equality edge' + ('s' if eq != 1 else ''))
    return ', '.join(parts)


def main() -> int:
    out_path = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_OUT

    lines = [
        '# Higgs query listings',
        '',
        'Generated by `scripts/export_queries.py` from the committed SQL in',
        '`input/queries/` — the exact text `sgx_join` and the SQLite reference',
        'both parse. Do not edit by hand; re-run the script.',
        '',
        'All queries use a fixed band width **W = 4 seconds** and run at each rung',
        'of the day ladder (1d / 2d / 3d). `SELECT *` is the only projection the',
        'engine supports, so every listing returns all columns of all tables.',
        '',
        '## Schema',
        '',
        '| Table | Columns | Source |',
        '|---|---|---|',
        '| `usersN` (application) | `UN_USERKEY, UN_INDEG, UN_OUTDEG, UN_ACTIVITY, UN_JOINDATE` | '
        'node table; `JOINDATE` = first activity timestamp, rebased to seconds since the window start |',
        '| `usersN` (microbenchmarks) | `UN_USERKEY, UN_INDEG, UN_OUTDEG, UN_ACTIVITY, UN_JOINDATE, UN_REGTIME` | '
        'same, with `REGTIME` = `JOINDATE` as the self-band column |',
        '| `followsN` | `FN_FOLLOWER, FN_FOLLOWED` | Higgs `social_network.edgelist` (equality hops only — it carries no timestamp) |',
        '',
        'Self-joins are materialised as numbered copies (`users1`, `users2`, …)',
        'because the engine addresses tables positionally; `usersN` files within a',
        'directory are identical apart from the column-name prefix.',
        '',
        'Data directories: `input/plaintext/higgs_<rung>` (application) and',
        '`input/plaintext/higgs_hops_<rung>` (microbenchmarks).',
        '',
    ]

    for title, blurb, entries in GROUPS:
        lines += [f'## {title}', '', blurb, '']
        for label, stem in entries:
            path = QDIR / f'{stem}.sql'
            if not path.exists():
                lines += [f'### {label} — `{stem}.sql` *(missing)*', '']
                continue
            sql = path.read_text().strip()
            tables, eq, band = analyse(sql)
            lines += [
                f'### {label} — `{stem}.sql`',
                '',
                f'*{describe(tables, eq, band)}; tables: '
                + ', '.join(f'`{t}`' for t in tables) + '*',
                '',
                '```sql',
                sql,
                '```',
                '',
            ]

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text('\n'.join(lines))
    count = sum(len(e) for _, _, e in GROUPS)
    print(f'{out_path}: {count} queries exported')
    return 0


if __name__ == '__main__':
    sys.exit(main())
